// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Route struct {
	RouteID   int32
	RouteName string
}

type Url struct {
	ID          string
	BaseRoute   int32
	Url         string
	CreatedAt   int64
	ExpiresAt   pgtype.Int8
	ClickCount  pgtype.Int8
	UtmSource   pgtype.Text
	UtmMedium   pgtype.Text
	UtmCampaign pgtype.Text
	UtmTerm     pgtype.Text
	UtmContent  pgtype.Text
}
