// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredUrls = `-- name: DeleteExpiredUrls :exec
DELETE FROM urls WHERE id = $1
`

func (q *Queries) DeleteExpiredUrls(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteExpiredUrls, id)
	return err
}

const getUrlFromID = `-- name: GetUrlFromID :one
SELECT urls.url, routes.route_name, urls.created_at, urls.expires_at
FROM urls INNER JOIN routes on urls.base_route = routes.route_id
WHERE urls.id = $1
`

type GetUrlFromIDRow struct {
	Url       string
	RouteName string
	CreatedAt int64
	ExpiresAt pgtype.Int8
}

func (q *Queries) GetUrlFromID(ctx context.Context, id string) (GetUrlFromIDRow, error) {
	row := q.db.QueryRow(ctx, getUrlFromID, id)
	var i GetUrlFromIDRow
	err := row.Scan(
		&i.Url,
		&i.RouteName,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const incrementUrlClickCount = `-- name: IncrementUrlClickCount :exec
UPDATE urls SET click_count = click_count + 1 WHERE id = $1
`

func (q *Queries) IncrementUrlClickCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementUrlClickCount, id)
	return err
}

const insertNewUrl = `-- name: InsertNewUrl :exec
INSERT INTO urls
  (id,url,created_at)
VALUES($1, $2, $3)
`

type InsertNewUrlParams struct {
	ID        string
	Url       string
	CreatedAt int64
}

func (q *Queries) InsertNewUrl(ctx context.Context, arg InsertNewUrlParams) error {
	_, err := q.db.Exec(ctx, insertNewUrl, arg.ID, arg.Url, arg.CreatedAt)
	return err
}
